build:
    image: default-bionic
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
        tests: true
        coverage:
            tests:
                override:
                    - command: composer coverage
                        coverage:
                            file: coverage.xml
                            format: clover
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                bitwise: false
                concatenation: true